<a href="https://colab.research.google.com/github/AdrianaCaetano/Data_Analysis_with_Python/blob/main/Tutorials/1_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analysis with Python 
### from freeCodeCamp Certification



In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([0, .5, 1, 1.5, 2])

In [ ]:
# Access individual elements 0 and 1 of array a

a[0],a[1]

(1, 2)

Slicing

In [ ]:
# array[start, end]
# array a from element 0 to the end

a[0:]

array([1, 2, 3, 4])

In [ ]:
# array a from element 1 to 3 (3 is not included)

a[1:3]

array([2, 3])

In [ ]:
# array a from element 1 to one before last element (-1)

a[1:-1]

array([2, 3])

In [ ]:
# different than Python lists, you can access multiple elements

b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [ ]:
# or you may pass a list to access the elements, whcih will return a numpy array

b[[0, 2, -1]]

array([0., 1., 2.])

Multi-dimensional arrays = Matrices

In [ ]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

In [ ]:
A.shape

(3, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

9

In [ ]:
B = np.array([
[
    [10,11,12],
    [13,14,15],
],
[
    [1,2,3],
    [4,5,6],
]
])

In [ ]:
B

array([[[10, 11, 12],
        [13, 14, 15]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [ ]:
B.shape

(2, 2, 3)

In [ ]:
# how many dimensions
B.ndim

3

In [ ]:
# total size of elements
B.size

12

Slicing matrices

In [ ]:
C = np.array([
  #  0  1  2  
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [ ]:
# silicing retrieves the row

C[1]

array([4, 5, 6])

In [ ]:
# to retrieve element at index 0 of the row 1

C[1][0]

4

In [ ]:
# or using the numpy selector [d1, d2, d3, ...]

C[1,0]   # row 1, element 0

4

In [ ]:
C[0:2]  # all elements of d1 (rows) from 0 to 2 (2 not included)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# array [d1 start:end, d2 start:end]

C[:,:2] # all elements of d1 (rows), until element 2 (not included) of d2 (columns)

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
C[:2,:2]

array([[1, 2],
       [4, 5]])

In [ ]:
C[2:, 2:]

array([[9]])

In [ ]:
C[:2, 2:]

array([[3],
       [6]])

In [ ]:
C[2:, :2]

array([[7, 8]])

In [ ]:
C[1] = np.array([10,10,10])
C

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [ ]:
C[2] = 99
C

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

Summary Statistics

In [ ]:
D = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]  
])
D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
D.sum()

45

In [ ]:
D.mean()

5.0

In [ ]:
D.std()

2.581988897471611

In [ ]:
D.var()

6.666666666666667

In [ ]:
D.sum(axis=0)  # sum of columns

array([12, 15, 18])

In [ ]:
D.sum(axis=1)  # sum of rows

array([ 6, 15, 24])

Broadcasting and vectorized operations

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# Array multiplied by 10
# optimized in Numpy
a * 10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# original array never changed
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Using = modifies the original array 
a += 100

In [ ]:
a

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [ ]:
# Python list can do the same thing, but it's not optimized as in Numpy

ls = [1,2,3,4]
ls

[1, 2, 3, 4]

In [ ]:
# Python list multiplied by 10

[i*10 for i in ls]

[10, 20, 30, 40]

Arrays and arrays operations
Both arrays must have the same shape

In [ ]:
a = np.arange(4)
b = np.array([10,10,10,10])

In [ ]:
a + b

array([10, 11, 12, 13])

In [ ]:
a * b

array([ 0, 10, 20, 30])

Boolean arrays

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
# select eleement using Python syntax
a[0], a[-1]

(0, 3)

In [ ]:
# select elements using numpy
a[[0,-1]]

array([0, 3])

In [ ]:
# select elements using True or False
a[[True, False, False, True]]

array([0, 3])

In [ ]:
a[[True, False, True, False]]

array([0, 2])

In [ ]:
a[[True, True, False, True]]

array([0, 1, 3])

In [ ]:
a >= 2

array([False, False,  True,  True])

In [ ]:
# filtering/selecting numerical arrays with a boolean condition
a[a>=2]

array([2, 3])

In [ ]:
a.mean()

1.5

In [ ]:
# retrieve all elements greeater than the mean
a[a > a.mean()]

array([2, 3])

In [ ]:
# retrieve all elements that are NOT greater than the mean
a[~(a>a.mean())]

array([0, 1])

In [ ]:
# OR
a[(a==0) | (a==2)]

array([0, 2])

In [ ]:
# AND
a[(a<=2) & (a % 2 == 0)]

array([0, 2])

In [ ]:
A = np.random.randint(100, size=(3,3))
A

array([[66, 58, 27],
       [39, 26, 45],
       [25, 31, 38]])

In [ ]:
A > 30

array([[ True,  True, False],
       [ True, False,  True],
       [False,  True,  True]])

In [ ]:
# boolean operations can be used to filter the data
A[A>30]

array([66, 58, 39, 45, 31, 38])

Linear Algebra

In [ ]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

B = np.array([
    [1,2],
    [10,20],
    [2,4]
])

In [ ]:
# Dot product
A.dot(B)

array([[ 27,  54],
       [ 66, 132],
       [105, 210]])

In [ ]:
# Cross product
A @ B

array([[ 27,  54],
       [ 66, 132],
       [105, 210]])

In [ ]:
# Transpose matrix
B.T

array([[ 1, 10,  2],
       [ 2, 20,  4]])

In [ ]:
B

array([[ 1,  2],
       [10, 20],
       [ 2,  4]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B.T @ A

array([[ 55,  68,  81],
       [110, 136, 162]])

Sizes of Objects in Memory

In [ ]:
import sys

In [ ]:
# an integer in python in bytes
sys.getsizeof(1)

28

In [ ]:
# long integer in Python
sys.getsizeof(10**100)

72

In [ ]:
# float in Python
sys.getsizeof(3.14)

24

In [ ]:
# numpy int size (in bytes)
np.dtype(int).itemsize

8

In [ ]:
# numpy int size (in bytes)
np.dtype(np.int8).itemsize

1

In [ ]:
# numpy float size
np.dtype(float).itemsize

8

In [ ]:
# Lists are even larger
sys.getsizeof([1])

64

In [ ]:
# Numpy array with one element
np.array([1]).nbytes

8

Performance

In [ ]:
ls = list(range(1000))


In [ ]:
a = np.arange(1000)

In [ ]:
%time np.sum(a**2)

CPU times: user 52 µs, sys: 5 µs, total: 57 µs
Wall time: 60.1 µs


332833500

In [ ]:
%time sum([x**2 for x in ls])

CPU times: user 334 µs, sys: 0 ns, total: 334 µs
Wall time: 337 µs


332833500

Useful Numpy Functions

random

In [ ]:
np.random.random(size=2)

array([0.93348173, 0.44794706])

In [ ]:
np.random.normal(size=2)

array([ 1.12606051, -0.69273006])

In [ ]:
np.random.rand(2,4)

array([[0.42859021, 0.04698305, 0.57222521, 0.59602908],
       [0.15628979, 0.05062392, 0.42808355, 0.57651622]])

arange

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(0,1,.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

reshape

In [ ]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

linspace

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
np.linspace(0,1,20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

zeros and ones

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,3),dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.empty((2,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

identity and eye

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8,4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8,4, k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
"Hello World"[6]

'W'