<a href="https://colab.research.google.com/github/AdrianaCaetano/Data_Analysis_with_Python/blob/main/Tutorials/4_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analysis with Python
### from freeCodeCamp Certification

# Data Cleaning Module

In [2]:
import numpy as np
import pandas as pd

# Missing Data

What does "missing data" mean? What is a missing value? It depends on the origin of the data and the context it was generated.

In [91]:
# For Python, all these values are considered "falsy":
falsy_values = (0, False, None, '', [], {})
any(falsy_values)

False

In [92]:
# Numpy has a special "nullable" value for numbers which is np.nan. It's NaN: "Not a number"
np.nan

nan

In [93]:
# The np.nan value is kind of a virus. Everything that it touches becomes np.nan
+ np.nan

nan

In [94]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [95]:
a.sum()

nan

In [96]:
a.mean()

nan

In [97]:
# This is better than regular None values, which in the previous examples would have raised an exception:
3 + None

TypeError: ignored

In [98]:
# For a numeric array, the None value is replaced by np.nan:
a = np.array([1, 2, 3, np.nan, None, 4], dtype='float')
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [99]:
# Numpy also supports an "Infinite" type:
np.inf

inf

In [100]:
# Which also behaves as a virus:
3 + np.inf

inf

In [102]:
np.inf/ 3

inf

In [103]:
np.inf / np.inf

nan

In [104]:
b = np.array([1, 2, 3, np.inf, np.nan, 4], dtype=float)
b

array([ 1.,  2.,  3., inf, nan,  4.])

In [105]:
b.sum()

nan

## Checking for `nan` and `inf`

In [106]:
np.isnan(np.nan)

True

In [107]:
np.isinf(np.inf)

True

In [108]:
# The joint operation can be performed with np.isfinite
np.isfinite(np.nan), np.isfinite(np.inf)

(False, False)

In [109]:
# np.isnan and np.isinf also take arrays as inputs, and return boolean arrays as results:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False,  True, False, False])

In [110]:
np.isinf(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False, False,  True, False])

In [111]:
np.isfinite(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([ True,  True,  True, False, False,  True])

## Filtering them out

In [112]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [113]:
# use a combination of the previous np.isnan + boolean arrays 
a[~np.isnan(a)]

array([1., 2., 3., 4.])

In [114]:
# Which is equivalent to:
a[np.isfinite(a)]

array([1., 2., 3., 4.])

In [115]:
# And with that result, all the operation can be now performed
a[np.isfinite(a)].sum()

10.0

In [116]:
a[np.isfinite(a)].mean()

2.5

# Handling Missing Data with Pandas

In [117]:
pd.isnull(np.nan)

True

In [118]:
pd.isnull(None)

True

In [119]:
pd.isna(np.nan)

True

In [120]:
pd.isna(None)

True

In [121]:
# the opposite ones also exist:
pd.notnull(None)

False

In [122]:
pd.notnull(np.nan)

False

In [123]:
pd.notna(np.nan)

False

In [124]:
pd.notnull(3)

True

In [125]:
# These functions also work with Series and DataFrames
pd.isnull(pd.Series([1, np.nan, 7]))

0    False
1     True
2    False
dtype: bool

In [126]:
pd.notnull(pd.Series([1, np.nan, 7]))

0     True
1    False
2     True
dtype: bool

In [127]:
pd.isnull(pd.DataFrame({
    'Column A': [1, np.nan, 7],
    'Column B': [np.nan, 2, 3],
    'Column C': [np.nan, 2, np.nan]
}))

Column A  Column B  Column C
0     False      True      True
1      True     False     False
2     False     False      True

## Pandas Operations with Missing Data

In [128]:
#  we could combine boolean selection + pd.isnull to filter out those nans and null values:
s = pd.Series([1, 2, 3, np.nan, np.nan, 4])
pd.notnull(s)

0     True
1     True
2     True
3    False
4    False
5     True
dtype: bool

In [129]:
pd.isnull(s)

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [130]:
pd.notnull(s).sum()

4

In [131]:
pd.isnull(s).sum()

2

In [132]:
s[pd.notnull(s)]

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

In [133]:
# But both notnull and isnull are also methods of Series and DataFrames, so we could use it that way:
s.isnull()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [134]:
s.notnull()

0     True
1     True
2     True
3    False
4    False
5     True
dtype: bool

In [135]:
s[s.notnull()]

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

## Dropping null values

In [136]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [137]:
s.dropna()

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

In [138]:
df = pd.DataFrame({
    'Column A': [1, np.nan, 30, np.nan],
    'Column B': [2, 8, 31, np.nan],
    'Column C': [np.nan, 9, 32, 100],
    'Column D': [5, 8, 34, 110],
})
df

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Column A  2 non-null      float64
 1   Column B  3 non-null      float64
 2   Column C  3 non-null      float64
 3   Column D  4 non-null      int64  
dtypes: float64(3), int64(1)
memory usage: 256.0 bytes


In [140]:
df.shape

(4, 4)

In [141]:
df.isnull()

Column A  Column B  Column C  Column D
0     False     False      True     False
1      True     False     False     False
2     False     False     False     False
3      True      True     False     False

In [142]:
df.isnull().sum()

Column A    2
Column B    1
Column C    1
Column D    0
dtype: int64

In [143]:
# The default dropna behavior will drop all the rows in which any null value is present:
df.dropna()


Column A  Column B  Column C  Column D
2      30.0      31.0      32.0        34

In [144]:
df.dropna(axis=1)  # axis='columns' also works

Column D
0         5
1         8
2        34
3       110

Any row or column that contains at least one null value will be dropped. Which can be, depending on the case, too extreme. You can control this behavior with the how parameter. Can be either 'any' or 'all'

In [145]:
df2 = pd.DataFrame({
    'Column A': [1, np.nan, 30],
    'Column B': [2, np.nan, 31],
    'Column C': [np.nan, np.nan, 100]
})
df2

Column A  Column B  Column C
0       1.0       2.0       NaN
1       NaN       NaN       NaN
2      30.0      31.0     100.0

In [146]:
df2.dropna(how='all')

Column A  Column B  Column C
0       1.0       2.0       NaN
2      30.0      31.0     100.0

In [147]:
df2.dropna(how='any')

Column A  Column B  Column C
2      30.0      31.0     100.0

In [148]:
# You can also use the thresh parameter to indicate a threshold (a minimum number) of non-null values for the row/column to be kept:
df2.dropna(thresh=3)

Column A  Column B  Column C
2      30.0      31.0     100.0

In [149]:
df.dropna(thresh=3)

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34

In [150]:
df.dropna(thresh=3, axis='columns')

Column B  Column C  Column D
0       2.0       NaN         5
1       8.0       9.0         8
2      31.0      32.0        34
3       NaN     100.0       110

## Filling null values on Series

In [151]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [152]:
s.fillna(0)

0    1.0
1    2.0
2    3.0
3    0.0
4    0.0
5    4.0
dtype: float64

In [153]:
s.fillna(s.mean())

0    1.0
1    2.0
2    3.0
3    2.5
4    2.5
5    4.0
dtype: float64

Filling nulls with contiguous (close) values

The method argument is used to fill null values with other values close to that null one

In [154]:
s.fillna(method='ffill') # forward fill, propagate last valid observation forward 

0    1.0
1    2.0
2    3.0
3    3.0
4    3.0
5    4.0
dtype: float64

In [155]:
s.fillna(method='bfill') # back fill, use next valid observation to fill gap.

0    1.0
1    2.0
2    3.0
3    4.0
4    4.0
5    4.0
dtype: float64

In [156]:
# This can still leave null values at the extremes of the Series/DataFrame:
pd.Series([np.nan, 3, np.nan, 9]).fillna(method='ffill')

0    NaN
1    3.0
2    3.0
3    9.0
dtype: float64

In [157]:
pd.Series([1, np.nan, 3, np.nan, np.nan]).fillna(method='bfill')

0    1.0
1    3.0
2    3.0
3    NaN
4    NaN
dtype: float64

## Filling null values on DataFrames

The fillna method also works on DataFrames, and it works similarly. The main differences are that you can specify the axis (as usual, rows or columns) to use to fill the values (specially for methods) and that you have more control on the values passed:

In [158]:
df

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [159]:
df.fillna({'Column A': 0, 'Column B': 99, 'Column C': df['Column C'].mean()})

Column A  Column B  Column C  Column D
0       1.0       2.0      47.0         5
1       0.0       8.0       9.0         8
2      30.0      31.0      32.0        34
3       0.0      99.0     100.0       110

In [160]:
df.fillna(method='ffill', axis=0)

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       1.0       8.0       9.0         8
2      30.0      31.0      32.0        34
3      30.0      31.0     100.0       110

In [161]:
df.fillna(method='ffill', axis=1)

Column A  Column B  Column C  Column D
0       1.0       2.0       2.0       5.0
1       NaN       8.0       9.0       8.0
2      30.0      31.0      32.0      34.0
3       NaN       NaN     100.0     110.0

## Check for NAs

The question is: Does this Series or DataFrame contain any missing value? The answer should be yes or no: True or False. 

By checking the length

In [162]:
missing_values = len(s.dropna()) != len(s)
missing_values

True

In [163]:
len(s)

6

In [164]:
s.dropna().count()

4

If there are missing values, s.dropna() will have less elements than s:

In [165]:
s.count()

4

More Pythonic solution any

The methods any and all check if either there's any True value in a Series or all the values are True. They work in the same way as in Python:

In [166]:
pd.Series([True, False, False]).any()

True

In [167]:
pd.Series([True, False, False]).all()

False

In [168]:
pd.Series([False, False, False]).all()

False

In [169]:
pd.Series([True, True, True]).all()

True

The isnull() method returned a Boolean Series with True values wherever there was a nan

In [170]:
s.isnull()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

So we can just use the any method with the boolean array returned:

In [171]:
pd.Series([1, np.nan]).isnull().any()

True

In [172]:
pd.Series([1, 2]).isnull().any()

False

In [173]:
s.isnull().any()

True

A more strict version would check only the values of the Series:

In [174]:
s.isnull().values

array([False, False, False,  True,  True, False])

In [175]:
s.isnull().values.any()

True

# Cleaning not-null values

After dealing with many datasets I can tell you that "missing data" is not such a big deal. The best thing that can happen is to clearly see values like np.nan. The only thing you need to do is just use methods like isnull and fillna/dropna and pandas will take care of the rest.

But sometimes, you can have invalid values that are not just "missing data" (None, or nan)

In [4]:
df = pd.DataFrame({
    'Sex': ['M', 'F', 'F', 'D', '?'],
    'Age': [29, 30, 24, 290, 25],
})
df

Sex  Age
0   M   29
1   F   30
2   F   24
3   D  290
4   ?   25

The previous DataFrame doesn't have any "missing value", but clearly has invalid data. 290 doesn't seem like a valid age, and D and ? don't correspond with any known sex category. How can you clean these not-missing, but clearly invalid values then?

## Finding Unique Values

In [5]:
df['Sex'].unique()

array(['M', 'F', 'D', '?'], dtype=object)

In [6]:
df['Sex'].value_counts()

F    2
M    1
D    1
?    1
Name: Sex, dtype: int64

In [7]:
# D is a typo and should be F instead
df['Sex'].replace('D', 'F')

0    M
1    F
2    F
3    F
4    ?
Name: Sex, dtype: object

In [8]:
# A dict can be used to replace all values at once in a column
df['Sex'].replace({'D': 'F', 'N': 'M'})

0    M
1    F
2    F
3    F
4    ?
Name: Sex, dtype: object

In [9]:
# or at a dataframe level
df.replace({
    'Sex': {
        'D': 'F',
        'N': 'M'
    },
    'Age': {
        290: 29
    }
})

Sex  Age
0   M   29
1   F   30
2   F   24
3   F   29
4   ?   25

In [10]:
# Establish a treshhold for acceptable age
df[df['Age']> 100]

Sex  Age
3   D  290

In [11]:
# Assume that the extra zero of any age above 100 is a typo

df.loc[df['Age'] > 100, 'Age'] = df.loc[df['Age'] > 100, 'Age'] / 10
df

Sex   Age
0   M  29.0
1   F  30.0
2   F  24.0
3   D  29.0
4   ?  25.0

## Duplicates in Series

It behaves differently between series and dataframes

In [12]:
ambassadors = pd.Series([
    'France',
    'United Kingdom',
    'United Kingdom',
    'Italy',
    'Germany',
    'Germany',
    'Germany',
], index=[
    'Gérard Araud',
    'Kim Darroch',
    'Peter Westmacott',
    'Armando Varricchio',
    'Peter Wittig',
    'Peter Ammon',
    'Klaus Scharioth '
])

In [13]:
ambassadors

Gérard Araud                  France
Kim Darroch           United Kingdom
Peter Westmacott      United Kingdom
Armando Varricchio             Italy
Peter Wittig                 Germany
Peter Ammon                  Germany
Klaus Scharioth              Germany
dtype: object

In [14]:
# Check if a country has more than one amabassador
ambassadors.duplicated() # first ocurrence is not a duplicate

Gérard Araud          False
Kim Darroch           False
Peter Westmacott       True
Armando Varricchio    False
Peter Wittig          False
Peter Ammon            True
Klaus Scharioth        True
dtype: bool

In [15]:
ambassadors.duplicated(keep='last') # npw the last occurrence is not a duplicate

Gérard Araud          False
Kim Darroch            True
Peter Westmacott      False
Armando Varricchio    False
Peter Wittig           True
Peter Ammon            True
Klaus Scharioth       False
dtype: bool

In [16]:
ambassadors.duplicated(keep=False) # mark all as duplicate

Gérard Araud          False
Kim Darroch            True
Peter Westmacott       True
Armando Varricchio    False
Peter Wittig           True
Peter Ammon            True
Klaus Scharioth        True
dtype: bool

In [17]:
# Exclude the duplicate values, keeping first
ambassadors.drop_duplicates()

Gérard Araud                  France
Kim Darroch           United Kingdom
Armando Varricchio             Italy
Peter Wittig                 Germany
dtype: object

In [18]:
# or keeping last one 
ambassadors.drop_duplicates(keep='last')

Gérard Araud                  France
Peter Westmacott      United Kingdom
Armando Varricchio             Italy
Klaus Scharioth              Germany
dtype: object

In [19]:
# or dropping all of the values with duplicates
ambassadors.drop_duplicates(keep=False)

Gérard Araud          France
Armando Varricchio     Italy
dtype: object

## Duplicates in DataFrames

In [20]:
players = pd.DataFrame({
    'Name': [
        'Kobe Bryant',
        'LeBron James',
        'Kobe Bryant',
        'Carmelo Anthony',
        'Kobe Bryant',
    ],
    'Pos': [
        'SG',
        'SF',
        'SG',
        'SF',
        'SF'
    ]
})
players

Name Pos
0      Kobe Bryant  SG
1     LeBron James  SF
2      Kobe Bryant  SG
3  Carmelo Anthony  SF
4      Kobe Bryant  SF

In [21]:
# Kobe is duplicated but has differnt values for position
players.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [22]:
# Specifying the column to check for duplicate names
players.duplicated(subset=['Name'])

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [23]:
# keep also applies
players.duplicated(subset=['Name'], keep='last')

0     True
1    False
2     True
3    False
4    False
dtype: bool

In [24]:
# and drop_duplicates behaves simmilarly
players.drop_duplicates()

Name Pos
0      Kobe Bryant  SG
1     LeBron James  SF
3  Carmelo Anthony  SF
4      Kobe Bryant  SF

In [25]:
players.drop_duplicates(subset=['Name'])

Name Pos
0      Kobe Bryant  SG
1     LeBron James  SF
3  Carmelo Anthony  SF

In [26]:
players.drop_duplicates(subset=['Name'], keep='last')

Name Pos
1     LeBron James  SF
3  Carmelo Anthony  SF
4      Kobe Bryant  SF

## Text Handling

In [33]:
df = pd.DataFrame({
    'Data': [
        '1987_M_US _1',
        '1990?_M_UK_1',
        '1992_F_US_2',
        '1970?_M_   IT_1',
        '1985_F_I  T_2'
]})
df

Data
0     1987_M_US _1
1     1990?_M_UK_1
2      1992_F_US_2
3  1970?_M_   IT_1
4    1985_F_I  T_2

In [28]:
# The single columns represent the values "year, Sex, Country and 
# number of children", but it's all been grouped in the same column and 
# separated by an underscore

# use the underscore to separate the values 
df['Data'].str.split('_')

0       [1987, M, US , 1]
1       [1990?, M, UK, 1]
2        [1992, F, US, 2]
3    [1970?, M,    IT, 1]
4      [1985, F, I  T, 2]
Name: Data, dtype: object

In [34]:
# or use the undescore to separate into columns
df = df['Data'].str.split('_', expand=True)
df

0  1      2  3
0   1987  M    US   1
1  1990?  M     UK  1
2   1992  F     US  2
3  1970?  M     IT  1
4   1985  F   I  T  2

In [36]:
# Then rename the columns
df.columns = ['Year', 'Sex', 'Country', 'No Children']

In [37]:
df

Year Sex Country No Children
0   1987   M     US            1
1  1990?   M      UK           1
2   1992   F      US           2
3  1970?   M      IT           1
4   1985   F    I  T           2

In [38]:
# check data for a given value
# contains takes a regex/pattern as first value, so we need to escape the ? 
# symbol as it has a special meaning for these patterns. 
df['Year'].str.contains('\?')

0    False
1     True
2    False
3     True
4    False
Name: Year, dtype: bool

In [39]:
# # Regular letters don't need escaping
df['Country'].str.contains('U')

0     True
1     True
2     True
3    False
4    False
Name: Country, dtype: bool

In [40]:
# remove blank spaces
df['Country'].str.strip() # lstrip and rstrip also exist

0      US
1      UK
2      US
3      IT
4    I  T
Name: Country, dtype: object

In [41]:
# or just replace
df['Country'].str.replace(' ', '')

0    US
1    UK
2    US
3    IT
4    IT
Name: Country, dtype: object

In [42]:
# replace and contains take regex patterns, which can make it easier to replace values in bulk
df['Year'].str.replace(r'(?P<year>\d{4})\?', lambda m: m.group('year'))

<ipython-input-42-95426881a013>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Year'].str.replace(r'(?P<year>\d{4})\?', lambda m: m.group('year'))


0    1987
1    1990
2    1992
3    1970
4    1985
Name: Year, dtype: object

All of these values have special methods associated with the domain of that column

.str for string values

.cat for categorical values

.dt for datetime values 
